version: '3'
services:
  server:
    build: server
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/data/current
      - /data/current/node_modules
  app:
    build: app
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/data/current
      - /data/current/node_modules
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: aaaaaa
      POSTGRES_DB: fruitmarketplace
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data:
    driver: local